FROM mcr.microsoft.com/dotnet/sdk:8.0.100

WORKDIR /app

# Installer les outils de développement
RUN dotnet tool install --global dotnet-ef && \
    dotnet tool install --global dotnet-format
ENV PATH="${PATH}:/root/.dotnet/tools"

# Copier les fichiers de solution
COPY EasySave.sln ./
COPY global.json ./

# Copier tous les fichiers .csproj de src/
COPY src/EasySave.UI/*.csproj ./src/EasySave.UI/
COPY src/EasySave.Core/*.csproj ./src/EasySave.Core/
COPY src/EasySave.Application/*.csproj ./src/EasySave.Application/
COPY src/EasySave.Backup/*.csproj ./src/EasySave.Backup/
COPY src/EasySave.Persistence/*.csproj ./src/EasySave.Persistence/
COPY src/EasySave.Localization/*.csproj ./src/EasySave.Localization/
COPY src/EasySave.Configuration/*.csproj ./src/EasySave.Configuration/
COPY src/EasySave.System/*.csproj ./src/EasySave.System/
COPY src/EasySave.State/*.csproj ./src/EasySave.State/
COPY src/EasyLog/*.csproj ./src/EasyLog/
COPY src/EasySave.Log/*.csproj ./src/EasySave.Log/
COPY src/EasySave.GUI/*.csproj ./src/EasySave.GUI/


# Copier TOUS les fichiers .csproj de tests/
COPY tests/EasyLog.Tests/*.csproj ./tests/EasyLog.Tests/
COPY tests/EasySave.Log.Tests/*.csproj ./tests/EasySave.Log.Tests/
COPY tests/EasySave.Backup.Tests/*.csproj ./tests/EasySave.Backup.Tests/
COPY tests/EasySave.Application.Tests/*.csproj ./tests/EasySave.Application.Tests/
COPY tests/EasySave.State.Tests/*.csproj ./tests/EasySave.State.Tests/
COPY tests/EasySave.Persistence.Tests/*.csproj ./tests/EasySave.Persistence.Tests/
COPY tests/EasySave.Localization.Tests/*.csproj ./tests/EasySave.Localization.Tests/
COPY tests/EasySave.Configuration.Tests/*.csproj ./tests/EasySave.Configuration.Tests/
COPY tests/EasySave.System.Tests/*.csproj ./tests/EasySave.System.Tests/

# Restaurer les dépendances
RUN dotnet restore

# Copier le reste du code
COPY . .

EXPOSE 5000

# Commande par défaut - démarrer l'application UI
CMD ["dotnet", "watch", "run", "--project", "src/EasySave.UI/EasySave.UI.csproj"]
