namespace EasySave.Localization;

/// <summary>
/// Defines all available localization keys used for translating UI text.
/// </summary>
public enum LocalizationKey
{
    menu_create,
    menu_list,
    menu_save,
    menu_params,
    menu_quit,
    menu,
    menu_params_locale,
    menu_params_log_path,
    menu_params_log_format,
    menu_manage_jobs,
    menu_job_details,
    menu_job_actions,
    menu_job_run,
    menu_job_update,
    menu_job_delete,
    menu_job_update_name,
    menu_job_update_source,
    menu_job_update_destination,
    menu_job_update_type,
    menu_job_update_save,
    back,
    backupjob_create_name,
    backupjob_create_source,
    backupjob_create_destination,
    backupjob_create_type,
    backupjob_type_differential,
    backupjob_type_incremental,
    backupjob_type_complete,
    backupjob_id,
    backupjob_name,
    backupjob_source,
    backupjob_destination,
    backupjob_type,
    backupjob_running,
    backupjob_completed,
    backupjob_updated,
    backupjob_delete_confirm,
    config_locale_fr,
    config_locale_en,
    ask_log_path,
    log_path_updated,
    log_path_reset,
    log_path_invalid,
    log_format_updated,
    log_format_restart_required,
    log_format_json,
    log_format_xml,
    input_string_invalid,
    backupjob_last_executed,
    backupjob_active,
    backupjob_never,
    input_number_invalid,
    input_backuptype_invalid,
    waiting_user,
    backupjob_created,
    backupjob_type_list,
    user_choice,
    ask_backupjob_save,
    backup_saving,
    backup_error,
    input_escape_to_cancel,
    input_enter_to_keep_current,
    backupjob_id_not_found,
    menu_delete,
    ask_backupjob_delete,
    backupjob_deleted,
    backupjob_created_named,
    backupjob_deleted_named,
    backupjob_updated_named,
    backupjob_completed_named,
    settings_current_language,
    settings_log_format_active,
    settings_log_format_pending,
    settings_log_directory_active_custom,
    settings_log_directory_active_default,
    settings_status_active_now,
    settings_status_pending_restart,
    job_update_unsaved_title,
    job_update_unsaved_question,
    job_update_unsaved_save_and_quit,
    job_update_unsaved_discard_and_quit,
    error,
    error_add_exists,
    error_parser_arg_null,
    error_parser_arg_invalid,
    error_file_null,
    error_default,
    error_job_not_found,
    error_max_id,
    error_file_transfer_failed,
    error_backup_type_invalid,
    error_file_not_found,
    error_directory_not_found,
    error_parts_empty,
    error_parts_null,
    error_business_software_running,

    // GUI
    gui_sidebar_create,
    gui_sidebar_manage,
    gui_sidebar_log,
    gui_sidebar_config,
    gui_config_title,
    gui_config_language,
    gui_config_log_format,
    gui_config_log_directory,
    gui_config_log_directory_watermark,
    gui_config_business_software,
    gui_config_business_software_watermark,
    gui_config_business_software_add,
    gui_config_business_software_empty,
    gui_config_reset,
    gui_config_save,
    gui_config_saved,
    gui_config_browse,
    gui_config_path_invalid,
    gui_home_description,
    gui_manage_title,
    gui_manage_subtitle,
    gui_manage_search,
    gui_manage_actions,
    gui_manage_running,
    gui_manage_confirm_run_title,
    gui_manage_confirm_run_message,
    gui_manage_confirm_delete_title,
    gui_manage_confirm_delete_message,
    gui_manage_btn_confirm,
    gui_manage_btn_cancel,
    gui_manage_btn_delete,
    gui_manage_tooltip_run,
    gui_manage_tooltip_modify,
    gui_manage_tooltip_delete,
    gui_manage_run_success,
    gui_manage_delete_success,
    gui_create_add_success,
    gui_create_subtitle,
    gui_create_backup_name,
    gui_create_source,
    gui_create_destination,
    gui_create_backup_type,
    gui_create_cancel,
    gui_create_create_job,
    gui_create_browse,
    gui_create_source_invalid,
    gui_create_destination_invalid,
    gui_create_name_required,
    gui_create_name_too_long,
    gui_create_title,
    gui_create_browse_source,
    gui_create_browse_destination,
    gui_create_error_io,
    gui_create_error_unexpected,
    gui_create_success,

    // Config - Encrypted Extensions
    gui_config_encrypted_extensions,
    gui_config_encrypted_extensions_watermark,
    gui_config_encrypted_extensions_add,
    gui_config_encrypted_extensions_empty,

    // Manage - Edit dialog
    gui_manage_edit_title,
    gui_manage_edit_save,
    gui_manage_edit_success,

    // Manage - Multi-select run
    gui_manage_run_selected,
    gui_manage_select_all,
    gui_manage_run_selected_success,
    gui_manage_confirm_run_selected_message,

    // Manage - Multi-select delete
    gui_manage_delete_selected,
    gui_manage_delete_selected_success,
    gui_manage_confirm_delete_selected_message,

    // Manage - Empty state
    gui_manage_empty_title,
    gui_manage_empty_subtitle,

    // Window controls
    gui_window_minimize,
    gui_window_maximize,
    gui_window_restore,
    gui_window_close
    gui_create_success,
    gui_home_description,

    // Log - Log viewer
    gui_log_history_subtitle,
    gui_log_search_date_watermark,
    gui_log_detail_subtitle,
    gui_log_search_log_watermark,
    gui_log_col_time,
    gui_log_col_status,
    gui_log_col_size,
    gui_log_col_duration,
    gui_log_col_encryption,
    gui_log_jobs_subtitle,
    gui_log_runs_subtitle,
    gui_log_entries_subtitle,
    gui_log_col_runs,
    gui_log_col_start,
    gui_log_col_end,
    gui_log_col_total_duration,
    gui_log_col_total_size,
    gui_log_col_format,
    gui_log_status_in_progress,
    gui_log_status_completed,
    gui_log_status_error,
}
