@startuml
left to right direction
skinparam packageStyle rectangle
skinparam shadowing false

actor "Utilisateur" as User

rectangle "EasySave 1.1" {
  usecase "Naviguer dans les\nmenus interactifs" as UC_Interactive

  usecase "Gerer les travaux\nde sauvegarde" as UC_ManageJobs
  usecase "Creer un travail" as UC_Create
  usecase "Lister les travaux" as UC_List
  usecase "Voir le detail\nd'un travail" as UC_Details
  usecase "Modifier un travail" as UC_Update
  usecase "Supprimer un travail" as UC_Delete
  usecase "Executer un travail" as UC_RunOne

  usecase "Gerer les modifs\nnon sauvegardees" as UC_Unsaved

  usecase "Executer via CLI" as UC_CLI
  usecase "Executer plusieurs\ntravaux (IDs)" as UC_RunMany

  usecase "Configurer application" as UC_Settings
  usecase "Changer la langue\n(FR/EN)" as UC_Lang
  usecase "Changer dossier\ndes logs" as UC_LogDir
  usecase "Changer format\ndes logs (JSON/XML)" as UC_LogFormat

  usecase "Consulter etat\ntemps reel (state.json)" as UC_State
  usecase "Consulter logs\njournaliers" as UC_Logs
}

User --> UC_Interactive
User --> UC_CLI
User --> UC_State
User --> UC_Logs

UC_Interactive .> UC_ManageJobs : <<include>>
UC_Interactive .> UC_Settings : <<include>>

UC_ManageJobs .> UC_Create : <<include>>
UC_ManageJobs .> UC_List : <<include>>
UC_ManageJobs .> UC_Details : <<include>>

UC_Details .> UC_Update : <<extend>>
UC_Details .> UC_Delete : <<extend>>
UC_Details .> UC_RunOne : <<extend>>

UC_Update .> UC_Unsaved : <<include>>

UC_Settings .> UC_Lang : <<include>>
UC_Settings .> UC_LogDir : <<include>>
UC_Settings .> UC_LogFormat : <<include>>

UC_CLI .> UC_RunMany : <<include>>
UC_RunMany .> UC_RunOne : <<include>>

@enduml
